import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const nunit = Nunito({
  weight: "500",
  subsets: ["latin"],
  variable: "--font-nunito",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunit.className}>
      <body className="mx-auto max-w-[1540px]">
        <div className="" >
     
          <Header />
          <hr className=" mt-[30px] mb-[30px] border border-amber-400" /> 
          {children}
        </div>
      </body>
    </html>
  );
}
