import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const nunit = Nunito({
  weight: "500",
  subsets: ["latin"],
  variable: "--font-nunito",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunit.className}>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body className="mx-auto max-w-[1540px]">
          <Header />
          <hr className="mt-[30px] mb-[30px] mx-[100px] border border-amber-400 " />
          {children}
      </body>
    </html>
  );
}
